<?php

$labels = array();
$labels['use'] = 'Użyj ';
$labels['autosync'] = 'Automatyczna synchronizacja podczas logowania';
$labels['authcode'] = 'Kod autoryzacyjny Google';
$labels['authcodelink'] = 'Kliknij, aby uzyskać kod autoryzacyjny Google';
$labels['sync'] = 'Synchronizacja Google';
$labels['syncnow'] = 'Synchronizuj';

$messages = array();
$messages['done'] = 'Zrobione.';
$messages['contactsfound'] = ' znalezione kontakty.';
$messages['noauthcode'] = 'Pobranie kodu autoryzacyjnego niemożliwe z powodu błędu uwierzytelniania.';
$messages['googleunreachable'] = 'Niemożliwe uzyskanie dostępu do usług Google: $error. Spróbuj później.';
$messages['googleforbidden'] = 'Błąd uwierzytelniania!';
